git:
  depth: false

branches:
  only:
    - travis
    - master

os: linux
dist: xenial
language: cpp
compiler: gcc
addons:
  apt:
    packages:
      - libfltk1.3-dev
      - fluid
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libavutil-dev

script:
  - ./build-appimage.sh

after_success:
  - >-
    [ "$TRAVIS_BRANCH" = "travis" ] &&
    wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh &&
    bash upload.sh build-appimage/MiniResizer-x86_64.AppImage

deploy:
  - on:
        branch: master
        condition: '$(uname -m) == x86_64'
    provider: releases
    file: build-appimage/MiniResizer-x86_64.AppImage 
    skip_cleanup: true
    api_key:
      secure: "3VobeAuLBRAjv2EG4jdIX7GKSm90ys1Bvf5B1GOj7PBpYqDa3E/YEcLHHhOaH9cGB2Y1f/cYNPyNflM6uHLjaM1u5VyaRvljQRS/zKXvgJRR9wwdasB5o+occBLao6LqDJQhgnmRC8bDDrFori+BwDQD76Z252JpRPrncGTTWE5yALVyPMP66FKK8sQjJ/1hBBsCss+Tof0mvDkYny7LDpoW1oaadxta8l4nwdz4PIgVX/0blDtcst9wdrOPVu+2qgpRhq2kGtvgw34GG0WfRvRooamjqunTOuWckBt0CHjdSZNoNoqYd9tz/+VYdp84ChU8KMO2MPBUYzaGyIwoIGewcfsNbWAduSgrUtUWQrC1RZbywbwHWfbCcxp4r8Kn5HcbbDkq3ezPLnzX2pZxVU/GtVMLn7p/BL5kWzbabGoEU6rNwmsVLgEbAksMNqQT8iuRkyXy7f88bgidSRPYzTpzZLxgntIuZZeh6XWN9cjxt7/zUe/j1RnZ4vtO4jC5msjr8x6EIf5GiiWK3jrDdLhka9uKrtyiXmWf701yqDZxFY1paMy4PQ5qzVBHhsDY4wL7ajpFUPUsjUZ3tlNFvPM7vwy9lx6gHUaRPuSi2EVfmjn6H8wlIqpL3iO1vojVNx0pRVH+WNfw9r+9D4SrDA6WIdlY1LzDy3lzORZ6fpg="
    tags: true
