include(CheckSymbolExists)

if(NOT DEFINED FFMPEG_USE_NEW_AVCODEC_API)
    message(STATUS "Checking if we should use the new packet decoding API")
    get_target_property(CMAKE_REQUIRED_INCLUDES FFMPEG_avcodec INTERFACE_INCLUDE_DIRECTORIES)
    get_target_property(CMAKE_REQUIRED_LIBRARIES FFMPEG_avcodec INTERFACE_LINK_LIBRARIES)
    check_symbol_exists("avcodec_send_packet" "libavcodec/avcodec.h" FFMPEG_USE_NEW_AVCODEC_API)
    if(FFMPEG_USE_NEW_AVCODEC_API) 
        message(STATUS "Checking if we should use the new packet decoding API - yes")
    else()
        message(STATUS "Checking if we should use the new packet decoding API - no")
    endif()
endif()
