function(option_add_list optname optdoc optdefault optlist)
    if(NOT DEFINED "CACHE{OPTION_${optname}}")
        set("OPTION_${optname}" "${optdefault}" CACHE STRING "${optdoc}")
        return()
    endif()
    if(NOT "$CACHE{OPTION_${optname}}" IN_LIST optlist)
        message(FATAL_ERROR "$CACHE{OPTION_${optname}} must have a value among ${optlist}")
    endif()
endfunction()
