name: Build and Deploy

on:
  push:
    branches:
      - ci
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libfltk1.3-dev \
            fluid \
            libavcodec-dev \
            libavformat-dev \
            libswscale-dev \
            libavutil-dev \
            cmake \
            fuse \
            build-essential

      - name: Build the AppImage
        run: ./build-appimage.sh

      - name: Upload to GitHub Releases
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v1
        with:
          files: build-appimage/MiniResizer-x86_64.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
